Hãy thiết kế hệ thống quản lý position cho một trading platform bằng python3, với một số yêu cầu sau:
1. trading platform cung cấp các thông tin sau:
    - maintenance_margin_rate=0.005
    - taker_fee=0.0004
    - maker_fee=0.0002
2. Mỗi position phải có các thông tin sau:
    - id: str (unique identifier for the position)
    - exchange: str 
    - symbol: str
    - entry_price: float
    - quantity: float
    - side: str (LONG/SHORT)
    - type: str (spot/futures)
    - open_fee: float
    - close_fee: float
    - position_size: float
    - leverage: float
    - stop_loss: float
    - take_profit: float
    - liquidation_price: float (optional)
    - max_price: float (optional)
    - min_price: float (optional)
    - risk_reward_ratio: float (optional)
    - run_up: float (optional)
    - drawdown: float (optional)
    - unrealized_pnl: float (optional)
    - realized_pnl: float (optional)
    - status: str (open/closed/liquidated)
    - entry_time: datetime
    - closed_time: datetime (nullable)
3. hãy tạo các hàm sau cho class PositionManager:
    - calculate_liquidation_price
    - calculate_open_fee
    - calculate_close_fee
    - open_position
    - modify_position_stop_loss
    - modify_position_take_profit
    - close_position
    - get_position_by_id
    - get_all_positions
    - check_position_status
    - check_stop_loss_hit
    - check_take_profit_hit
    - calculate_pnl
    - calculate_pnl_with_fees
    - calculate_pnl_percentage
    - calculate_unrealized_pnl
    - calculate_unrealized_pnl_percentage
    - calculate_position_run_up
    - calculate_position_drawdown
    - calculate_position_size
    - calculate_effective_leverage
    - calculate_optimal_leverage
    - calculate_hedging_ratio
    - calculate_delta_neutral_position
    - calculate_position_risk_reward
    - calculate_risk_metrics
    - update_position
    - auto_track_position
    - get_position_summary
    - get_all_position_summary